---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    image: confluentinc/cp-kafka:7.3.1
    hostname: kafka0
    container_name: kafka0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "8090:8090"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: "kafka0"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
      KAFKA_LOG_RETENTION_BYTES: 26214400 # set max partition size equal to 25MB
  kafka1:
    image: confluentinc/cp-kafka:7.3.1
    hostname: kafka1
    container_name: kafka1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9192:9192"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29192,PLAINTEXT_HOST://localhost:9192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: "kafka1"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
      KAFKA_LOG_RETENTION_BYTES: 26214400
      
  kafka2:
    image: confluentinc/cp-kafka:7.3.1
    hostname: kafka2
    container_name: kafka2
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9292:9292"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29292,PLAINTEXT_HOST://localhost:9292
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_JMX_HOSTNAME: "kafka2"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=kafka2 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
      KAFKA_LOG_RETENTION_BYTES: 26214400

  topics_setup:
    image: confluentinc/cp-kafka:7.3.1
    hostname: topics_setup
    container_name: topics_setup
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - kafka2
    volumes:
      - ./messagingBrokerLayer/setup_topics.sh:/setup_topics.sh
    entrypoint: sh -c "/setup_topics.sh"
    stdin_open: true
    tty: true
    
  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    hostname: cmak
    container_name: cmak
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"

  cmak2zk:
    image: ghcr.io/eshepelyuk/dckr/cmak2zk:latest
    restart: on-failure
    container_name: cmak2zk
    command:
      - 'zookeeper:2181'
      - '/app/etc/cmak_cluster_config.yaml'
    depends_on:
      - "zookeeper"
    volumes:
      - "${PWD}/messagingBrokerLayer/cmak_cluster_config.yaml:/app/etc/cmak_cluster_config.yaml:ro"

  hbase:
    image: dajobe/hbase
    hostname: hbase
    container_name: hbase
    ports:
      - "16010:16010" # Master Web UI
      - "8080:8080"   # REST API
      - "8085:8085"   # REST UI
      - "9090:9090"   # Thrift API
      - "9095:9095"   # Thrift UI
    volumes:
      - ${PWD}/dataStorageLayer/hbase_files/data:/data

  grafana:
    image: grafana/grafana-oss
    hostname: grafana
    container_name: grafana_docker
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "golioth-websocket-datasource"
    # volumes:
    #   - ../presentationLayer:/imports_exports